#use_frameworks!
platform :ios, '11.0'

target 'BehaviourAnalyzer_Example' do
  pod 'BehaviourAnalyzer', :path => '../'

  target 'BehaviourAnalyzer_Tests' do
    inherit! :search_paths

    
  end
end
